export const USUARIO_LOGIN_INICIO = "USUARIO_LOGIN_INICIO";
export const USUARIO_LOGIN_EXITO = "USUARIO_LOGIN_EXITO";
export const USUARIO_LOGIN_ERROR = "USUARIO_LOGIN_ERROR";

export const USUARIO_COMPANY_INICIO = "USUARIO_COMPANY_INICIO";
export const USUARIO_COMPANY_EXITO = "USUARIO_COMPANY_EXITO";
export const USUARIO_COMPANY_ERROR = "USUARIO_COMPANY_ERROR";

export const USUARIO_LOGOUT = "USUARIO_LOGOUT";

export const USERS_GETALL_INICIO = "USERS_GETALL_INICIO";
export const USERS_GETALL_EXITO = "USERS_GETALL_EXITO";
export const USERS_GETALL_ERROR = "USERS_GETALL_ERROR";

export const COMPANY_SELECCIONAR_INICIO = "COMPANY_SELECCIONAR_INICIO";
export const COMPANY_SELECCIONAR_EXITO = "COMPANY_SELECCIONAR_EXITO";
export const COMPANY_SELECCIONAR_ERROR = "COMPANY_SELECCIONAR_ERROR";

export const ROL_SELECCIONAR_INICIO = "ROL_SELECCIONAR_INICIO";
export const ROL_SELECCIONAR_EXITO = "ROL_SELECCIONAR_EXITO";
export const ROL_SELECCIONAR_ERROR = "ROL_SELECCIONAR_ERROR";

export const LOGIN_TRUE_INICIO = "LOGIN_TRUE_INICIO";
export const LOGIN_TRUE_EXITO = "LOGIN_TRUE_EXITO";
export const LOGIN_TRUE_ERROR = "LOGIN_TRUE_ERROR";

export const CREATE_USER_INICIO = "CREATE_USER_INICIO";
export const CREATE_USER_EXITO = "CREATE_USER_EXITO";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const LEVANTAR_VENTANA = "LEVANTAR_VENTANA";
export const BOTON_LOADING = "BOTON_LOADING";

export const CAMBIO_PASSWORD_EXITO = "CAMBIO_PASSWORD_EXITO";
export const CAMBIO_PASSWORD_INICIO = "CAMBIO_PASSWORD_INICIO";
export const CAMBIO_PASSWORD_ERROR = "CAMBIO_PASSWORD_ERROR";
export const CAMBIO_PASSWORD = "CAMBIO_PASSWORD";


export const LISTA_DIRECCIONES = "LISTA_DIRECCIONES";
