export const TIPO_PAGO = 'TIPO_PAGO';
export const NOMBRE_BANCO = 'NOMBRE_BANCO';
export const NUMERO_DOCUMENTO = 'NUMERO_DOCUMENTO';
export const TOTAL_DOCUMENTO = 'TOTAL_DOCUMENTO';

export const CONTRASEÑA_DOCUMENTO = 'CONTRASEÑA_DOCUMENTO';
export const TRAMITE_CONTRASEÑA = 'TRAMITE_CONTRASEÑA';
export const FIRMA_DOCUMENTO = 'FIRMA_DOCUMENTO';
export const NO_TIENE_FIRMA_DOCUMENTO = 'NO_TIENE_FIRMA_DOCUMENTO';

export const CONTADO = 'CONTADO';
export const CREDITO = 'CREDITO';
export const RECIBIO_CLIENTE = 'RECIBIO_CLIENTE';
export const RECIBIO_CLIENTE_ENTREGA = 'RECIBIO_CLIENTE_ENTREGA';

export const COMENTARIO_NO_ENTREGADO = 'COMENTARIO_NO_ENTREGADO';
export const FECHA_COBRO = 'FECHA_COBRO';

export const ENVIO_A_FACTURADOR_INICIO = 'ENVIO_A_FACTURADOR_INICIO';
export const ENVIO_A_FACTURADOR_EXITO = 'ENVIO_A_FACTURADOR_EXITO';
export const ENVIO_A_FACTURADOR_ERROR = 'ENVIO_A_FACTURADOR_ERROR';

export const INICIO_lIQUIDACION = 'INICIO_lIQUIDACION';
export const EXITO_lIQUIDACION = 'EXITO_lIQUIDACION';
export const ERROR_lIQUIDACION = 'ERROR_lIQUIDACION';

export const INICIO_lIQUIDACION_ENTREGA = 'INICIO_lIQUIDACION_ENTREGA';
export const EXITO_lIQUIDACION_ENTREGA = 'EXITO_lIQUIDACION_ENTREGA';
export const ERROR_lIQUIDACION_ENTREGA = 'ERROR_lIQUIDACION_ENTREGA';

export const SAVE_CONFIRMACION_ENTREGA = 'SAVE_CONFIRMACION_ENTREGA';

export const CERRAR_SNACK_LIQUIDACION = "CERRAR_SNACK_LIQUIDACION";
export const CERRAR_SNACK_LIQUIDACION_ENTREGA = "CERRAR_SNACK_LIQUIDACION_ENTREGA";

