export const INICIO_REGISTRO_UBICACION = 'INICIO_REGISTRO_UBICACION';
export const EXITO_REGISTRO_UBICACION = 'EXITO_REGISTRO_UBICACION';
export const ERROR_REGISTRO_UBICACION = 'ERROR_REGISTRO_UBICACION';
export const SAVE_LOCALSTORAGE = 'SAVE_LOCALSTORAGE';
export const CERRAR_SNAKE_REGISTER = 'CERRAR_SNAKE_REGISTER';

export const INICIO_PENDIENTE = 'INICIO_PENDIENTE';
export const EXITO_PENDIENTE = 'EXITO_PENDIENTE';
export const ERROR_PENDIENTE = 'ERROR_PENDIENTE';

export const INICIO_UPDATE_VISITA = 'INICIO_UPDATE_VISITA';
export const EXITO_UPDATE_VISITA = 'EXITO_UPDATE_VISITA';
export const ERROR_UPDATE_VISITA = 'ERROR_UPDATE_VISITA';
export const CERRAR_SNAKE_UPDATE_VISITA = 'CERRAR_SNAKE_UPDATE_VISITA';

export const INICIO_REALIZADO = 'INICIO_REALIZADO';
export const EXITO_REALIZADO = 'EXITO_REALIZADO';
export const ERROR_REALIZADO = 'ERROR_REALIZADO';

export const INICIO_SEARCH_CARCODE = 'INICIO_SEARCH_CARCODE';
export const EXITO_SEARCH_CARCODE = 'EXITO_SEARCH_CARCODE';
export const ERROR_SEARCH_CARCODE = 'ERROR_SEARCH_CARCODE';

export const INICIO_REGISTRO_UNICO = 'INICIO_REGISTRO_UNICO';
export const EXITO_REGISTRO_UNICO = 'EXITO_REGISTRO_UNICO';
export const ERROR_REGISTRO_UNICO = 'ERROR_REGISTRO_UNICO';
